services:
  - type: web
    name: networq-global
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npx srvx serve --prod --entry dist/server/server.js -s ../client
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
