/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWebDesignRouteImport } from './routes/services.web-design'
import { Route as ServicesVideoMultimediaRouteImport } from './routes/services.video-multimedia'
import { Route as ServicesSocialMediaRouteImport } from './routes/services.social-media'
import { Route as ServicesSeoRouteImport } from './routes/services.seo'
import { Route as ServicesPerformanceRouteImport } from './routes/services.performance'
import { Route as ServicesLocalBusinessRouteImport } from './routes/services.local-business'
import { Route as ServicesEmergingRouteImport } from './routes/services.emerging'
import { Route as ServicesContentRouteImport } from './routes/services.content'
import { Route as ServicesBusinessGrowthRouteImport } from './routes/services.business-growth'
import { Route as ServicesBrandCreativeRouteImport } from './routes/services.brand-creative'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebDesignRoute = ServicesWebDesignRouteImport.update({
  id: '/web-design',
  path: '/web-design',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesVideoMultimediaRoute = ServicesVideoMultimediaRouteImport.update({
  id: '/video-multimedia',
  path: '/video-multimedia',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSocialMediaRoute = ServicesSocialMediaRouteImport.update({
  id: '/social-media',
  path: '/social-media',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPerformanceRoute = ServicesPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesLocalBusinessRoute = ServicesLocalBusinessRouteImport.update({
  id: '/local-business',
  path: '/local-business',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEmergingRoute = ServicesEmergingRouteImport.update({
  id: '/emerging',
  path: '/emerging',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesContentRoute = ServicesContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBusinessGrowthRoute = ServicesBusinessGrowthRouteImport.update({
  id: '/business-growth',
  path: '/business-growth',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesBrandCreativeRoute = ServicesBrandCreativeRouteImport.update({
  id: '/brand-creative',
  path: '/brand-creative',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/brand-creative': typeof ServicesBrandCreativeRoute
  '/services/business-growth': typeof ServicesBusinessGrowthRoute
  '/services/content': typeof ServicesContentRoute
  '/services/emerging': typeof ServicesEmergingRoute
  '/services/local-business': typeof ServicesLocalBusinessRoute
  '/services/performance': typeof ServicesPerformanceRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/video-multimedia': typeof ServicesVideoMultimediaRoute
  '/services/web-design': typeof ServicesWebDesignRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/brand-creative': typeof ServicesBrandCreativeRoute
  '/services/business-growth': typeof ServicesBusinessGrowthRoute
  '/services/content': typeof ServicesContentRoute
  '/services/emerging': typeof ServicesEmergingRoute
  '/services/local-business': typeof ServicesLocalBusinessRoute
  '/services/performance': typeof ServicesPerformanceRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/video-multimedia': typeof ServicesVideoMultimediaRoute
  '/services/web-design': typeof ServicesWebDesignRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/brand-creative': typeof ServicesBrandCreativeRoute
  '/services/business-growth': typeof ServicesBusinessGrowthRoute
  '/services/content': typeof ServicesContentRoute
  '/services/emerging': typeof ServicesEmergingRoute
  '/services/local-business': typeof ServicesLocalBusinessRoute
  '/services/performance': typeof ServicesPerformanceRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/social-media': typeof ServicesSocialMediaRoute
  '/services/video-multimedia': typeof ServicesVideoMultimediaRoute
  '/services/web-design': typeof ServicesWebDesignRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/careers'
    | '/contact'
    | '/services'
    | '/services/brand-creative'
    | '/services/business-growth'
    | '/services/content'
    | '/services/emerging'
    | '/services/local-business'
    | '/services/performance'
    | '/services/seo'
    | '/services/social-media'
    | '/services/video-multimedia'
    | '/services/web-design'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/careers'
    | '/contact'
    | '/services'
    | '/services/brand-creative'
    | '/services/business-growth'
    | '/services/content'
    | '/services/emerging'
    | '/services/local-business'
    | '/services/performance'
    | '/services/seo'
    | '/services/social-media'
    | '/services/video-multimedia'
    | '/services/web-design'
  id:
    | '__root__'
    | '/'
    | '/careers'
    | '/contact'
    | '/services'
    | '/services/brand-creative'
    | '/services/business-growth'
    | '/services/content'
    | '/services/emerging'
    | '/services/local-business'
    | '/services/performance'
    | '/services/seo'
    | '/services/social-media'
    | '/services/video-multimedia'
    | '/services/web-design'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/web-design': {
      id: '/services/web-design'
      path: '/web-design'
      fullPath: '/services/web-design'
      preLoaderRoute: typeof ServicesWebDesignRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/video-multimedia': {
      id: '/services/video-multimedia'
      path: '/video-multimedia'
      fullPath: '/services/video-multimedia'
      preLoaderRoute: typeof ServicesVideoMultimediaRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/social-media': {
      id: '/services/social-media'
      path: '/social-media'
      fullPath: '/services/social-media'
      preLoaderRoute: typeof ServicesSocialMediaRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/performance': {
      id: '/services/performance'
      path: '/performance'
      fullPath: '/services/performance'
      preLoaderRoute: typeof ServicesPerformanceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/local-business': {
      id: '/services/local-business'
      path: '/local-business'
      fullPath: '/services/local-business'
      preLoaderRoute: typeof ServicesLocalBusinessRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/emerging': {
      id: '/services/emerging'
      path: '/emerging'
      fullPath: '/services/emerging'
      preLoaderRoute: typeof ServicesEmergingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/content': {
      id: '/services/content'
      path: '/content'
      fullPath: '/services/content'
      preLoaderRoute: typeof ServicesContentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/business-growth': {
      id: '/services/business-growth'
      path: '/business-growth'
      fullPath: '/services/business-growth'
      preLoaderRoute: typeof ServicesBusinessGrowthRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/brand-creative': {
      id: '/services/brand-creative'
      path: '/brand-creative'
      fullPath: '/services/brand-creative'
      preLoaderRoute: typeof ServicesBrandCreativeRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesBrandCreativeRoute: typeof ServicesBrandCreativeRoute
  ServicesBusinessGrowthRoute: typeof ServicesBusinessGrowthRoute
  ServicesContentRoute: typeof ServicesContentRoute
  ServicesEmergingRoute: typeof ServicesEmergingRoute
  ServicesLocalBusinessRoute: typeof ServicesLocalBusinessRoute
  ServicesPerformanceRoute: typeof ServicesPerformanceRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesSocialMediaRoute: typeof ServicesSocialMediaRoute
  ServicesVideoMultimediaRoute: typeof ServicesVideoMultimediaRoute
  ServicesWebDesignRoute: typeof ServicesWebDesignRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesBrandCreativeRoute: ServicesBrandCreativeRoute,
  ServicesBusinessGrowthRoute: ServicesBusinessGrowthRoute,
  ServicesContentRoute: ServicesContentRoute,
  ServicesEmergingRoute: ServicesEmergingRoute,
  ServicesLocalBusinessRoute: ServicesLocalBusinessRoute,
  ServicesPerformanceRoute: ServicesPerformanceRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesSocialMediaRoute: ServicesSocialMediaRoute,
  ServicesVideoMultimediaRoute: ServicesVideoMultimediaRoute,
  ServicesWebDesignRoute: ServicesWebDesignRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
